AllCops:
  TargetRubyVersion: 2.4

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
  
Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 12

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Severity: warning

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Severity: warning

Style/GuardClause:
  Severity: warning

Style/NegatedIf:
  Severity: warning

Style/SpaceInsideBrackets:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  Enabled: false
