AllCops:
  TargetRubyVersion: 2.5

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Metrics/AbcSize:
  Max: 80

Metrics/ClassLength:
  Max: 600

Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 24

Metrics/LineLength:
  Max: 320

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 600

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 24

Naming/VariableNumber:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Severity: warning

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NegatedIf:
  Severity: warning

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  MinSize: 6

Style/TrailingCommaInArrayLiteral:
  Enabled: false
